###############
# Global params

  # for records
  description:        'EP-SuRE ECN data analysis pipeline'
  dataset:            'ECN runs (pDNA + cDNA), SE sequencing'

  # params
  metadata:
    mate_suffix:      '_R1' 
    input_format:     'fastq.gz'

  dir:
    fastq_dir:        '/DATA/projects/epmatrix/mouse/DAT_EP010_EP013/ecn/Raw'
    results:          'Results'
    logs:             'Logs'
    conda_env:        '/YOURDIR/UpstreamPipeline/envs'
    snakerules:       '/YOURDIR/UpstreamPipeline/rules'

################
# Notes:
# dry run this snakemake pipeline
#   snakemake -n --snakefile /YOURDIR/UpstreamPipeline/workflows/ecn.wf --configfile /YOURDIR/UpstreamPipeline/config/config_ecn.yaml

# run this snakemake pipeline
#   snakemake --cores 24 --use-conda --snakefile /YOURDIR/UpstreamPipeline/workflows/ecn.wf --configfile /YOURDIR/UpstreamPipeline/config/config_ecn.yaml
